### ISSUE TITLE
Grapher doesn't reconnect if data vault gets new ID

### ISSUE THREAD

**Issue by JulianSKelly** [martinisgroup/labrad-manager-delphi#5]

**Comment by ejeffrey** [comment]
The datavault shouldn't get a new ID -- The server ID should be reserved
after the first connection.  Can you describe how this happened?

**Comment by maffoo** [comment]
This is happening when we're switching between the scala and delphi manager, so the IDs are different. Not something we do in practice, but would still be nice to fix.
